# Generated by Django 6.0.2 on 2026-03-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_organizations_owner_alter_memberships_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='code_hash',
        ),
    ]
