# Generated by Django 6.0.2 on 2026-03-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organizationcode_remove_organizations_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcode',
            name='organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.organizations'),
            preserve_default=False,
        ),
    ]
